
//this file is generated by samples/generateInstrumentList.m

class Instruments {

	static get() {

		const serverUrl = window.location.origin;

		const instruments = new Map();

		/////////
		// Bassoon ( samples/external/bassoon/ )
		let 	instrument  = {
			displayName: 'Bassoon',
			sampleNumber: '10',
			baseUrl: serverUrl + '/samples/external/bassoon/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'A2': 'A2.mp3',
				'A3': 'A3.mp3',
				'A4': 'A4.mp3',
				'C3': 'C3.mp3',
				'C4': 'C4.mp3',
				'C5': 'C5.mp3',
				'E4': 'E4.mp3',
				'G2': 'G2.mp3',
				'G3': 'G3.mp3',
				'G4': 'G4.mp3',
			},
		};

		instruments.set('Bassoon',instrument);


		/////////
		// Piano ( samples/external/piano/ )
			instrument  = {
			displayName: 'Piano',
			sampleNumber: '85',
			baseUrl: serverUrl + '/samples/external/piano/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'A1': 'A1.mp3',
				'A2': 'A2.mp3',
				'A3': 'A3.mp3',
				'A4': 'A4.mp3',
				'A5': 'A5.mp3',
				'A6': 'A6.mp3',
				'A7': 'A7.mp3',
				'A#1': 'As1.mp3',
				'A#2': 'As2.mp3',
				'A#3': 'As3.mp3',
				'A#4': 'As4.mp3',
				'A#5': 'As5.mp3',
				'A#6': 'As6.mp3',
				'A#7': 'As7.mp3',
				'B1': 'B1.mp3',
				'B2': 'B2.mp3',
				'B3': 'B3.mp3',
				'B4': 'B4.mp3',
				'B5': 'B5.mp3',
				'B6': 'B6.mp3',
				'B7': 'B7.mp3',
				'C1': 'C1.mp3',
				'C2': 'C2.mp3',
				'C3': 'C3.mp3',
				'C4': 'C4.mp3',
				'C5': 'C5.mp3',
				'C6': 'C6.mp3',
				'C7': 'C7.mp3',
				'C8': 'C8.mp3',
				'C#1': 'Cs1.mp3',
				'C#2': 'Cs2.mp3',
				'C#3': 'Cs3.mp3',
				'C#4': 'Cs4.mp3',
				'C#5': 'Cs5.mp3',
				'C#6': 'Cs6.mp3',
				'C#7': 'Cs7.mp3',
				'D1': 'D1.mp3',
				'D2': 'D2.mp3',
				'D3': 'D3.mp3',
				'D4': 'D4.mp3',
				'D5': 'D5.mp3',
				'D6': 'D6.mp3',
				'D7': 'D7.mp3',
				'D#1': 'Ds1.mp3',
				'D#2': 'Ds2.mp3',
				'D#3': 'Ds3.mp3',
				'D#4': 'Ds4.mp3',
				'D#5': 'Ds5.mp3',
				'D#6': 'Ds6.mp3',
				'D#7': 'Ds7.mp3',
				'E1': 'E1.mp3',
				'E2': 'E2.mp3',
				'E3': 'E3.mp3',
				'E4': 'E4.mp3',
				'E5': 'E5.mp3',
				'E6': 'E6.mp3',
				'E7': 'E7.mp3',
				'F1': 'F1.mp3',
				'F2': 'F2.mp3',
				'F3': 'F3.mp3',
				'F4': 'F4.mp3',
				'F5': 'F5.mp3',
				'F6': 'F6.mp3',
				'F7': 'F7.mp3',
				'F#1': 'Fs1.mp3',
				'F#2': 'Fs2.mp3',
				'F#3': 'Fs3.mp3',
				'F#4': 'Fs4.mp3',
				'F#5': 'Fs5.mp3',
				'F#6': 'Fs6.mp3',
				'F#7': 'Fs7.mp3',
				'G1': 'G1.mp3',
				'G2': 'G2.mp3',
				'G3': 'G3.mp3',
				'G4': 'G4.mp3',
				'G5': 'G5.mp3',
				'G6': 'G6.mp3',
				'G7': 'G7.mp3',
				'G#1': 'Gs1.mp3',
				'G#2': 'Gs2.mp3',
				'G#3': 'Gs3.mp3',
				'G#4': 'Gs4.mp3',
				'G#5': 'Gs5.mp3',
				'G#6': 'Gs6.mp3',
				'G#7': 'Gs7.mp3',
			},
		};

		instruments.set('Piano',instrument);


		/////////
		// Saxophone ( samples/external/saxophone/ )
			instrument  = {
			displayName: 'Saxophone',
			sampleNumber: '32',
			baseUrl: serverUrl + '/samples/external/saxophone/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'A4': 'A4.mp3',
				'A5': 'A5.mp3',
				'A#3': 'As3.mp3',
				'A#4': 'As4.mp3',
				'B3': 'B3.mp3',
				'B4': 'B4.mp3',
				'C4': 'C4.mp3',
				'C5': 'C5.mp3',
				'C#3': 'Cs3.mp3',
				'C#4': 'Cs4.mp3',
				'C#5': 'Cs5.mp3',
				'D3': 'D3.mp3',
				'D4': 'D4.mp3',
				'D5': 'D5.mp3',
				'D#3': 'Ds3.mp3',
				'D#4': 'Ds4.mp3',
				'D#5': 'Ds5.mp3',
				'E3': 'E3.mp3',
				'E4': 'E4.mp3',
				'E5': 'E5.mp3',
				'F3': 'F3.mp3',
				'F4': 'F4.mp3',
				'F5': 'F5.mp3',
				'F#3': 'Fs3.mp3',
				'F#4': 'Fs4.mp3',
				'F#5': 'Fs5.mp3',
				'G3': 'G3.mp3',
				'G4': 'G4.mp3',
				'G5': 'G5.mp3',
				'G#3': 'Gs3.mp3',
				'G#4': 'Gs4.mp3',
				'G#5': 'Gs5.mp3',
			},
		};

		instruments.set('Saxophone',instrument);


		/////////
		// Organ ( samples/external/organ/ )
			instrument  = {
			displayName: 'Organ',
			sampleNumber: '21',
			baseUrl: serverUrl + '/samples/external/organ/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'A1': 'A1.mp3',
				'A2': 'A2.mp3',
				'A3': 'A3.mp3',
				'A4': 'A4.mp3',
				'A5': 'A5.mp3',
				'C1': 'C1.mp3',
				'C2': 'C2.mp3',
				'C3': 'C3.mp3',
				'C4': 'C4.mp3',
				'C5': 'C5.mp3',
				'C6': 'C6.mp3',
				'D#1': 'Ds1.mp3',
				'D#2': 'Ds2.mp3',
				'D#3': 'Ds3.mp3',
				'D#4': 'Ds4.mp3',
				'D#5': 'Ds5.mp3',
				'F#1': 'Fs1.mp3',
				'F#2': 'Fs2.mp3',
				'F#3': 'Fs3.mp3',
				'F#4': 'Fs4.mp3',
				'F#5': 'Fs5.mp3',
			},
		};

		instruments.set('Organ',instrument);


		/////////
		// Harp ( samples/external/harp/ )
			instrument  = {
			displayName: 'Harp',
			sampleNumber: '23',
			baseUrl: serverUrl + '/samples/external/harp/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'A2': 'A2.mp3',
				'A4': 'A4.mp3',
				'A6': 'A6.mp3',
				'B1': 'B1.mp3',
				'B3': 'B3.mp3',
				'B5': 'B5.mp3',
				'B6': 'B6.mp3',
				'C3': 'C3.mp3',
				'C5': 'C5.mp3',
				'D2': 'D2.mp3',
				'D4': 'D4.mp3',
				'D6': 'D6.mp3',
				'D7': 'D7.mp3',
				'E1': 'E1.mp3',
				'E3': 'E3.mp3',
				'E5': 'E5.mp3',
				'F2': 'F2.mp3',
				'F4': 'F4.mp3',
				'F6': 'F6.mp3',
				'F7': 'F7.mp3',
				'G1': 'G1.mp3',
				'G3': 'G3.mp3',
				'G5': 'G5.mp3',
			},
		};

		instruments.set('Harp',instrument);


		/////////
		// Guitar Electric ( samples/external/guitar-electric/ )
			instrument  = {
			displayName: 'Guitar Electric',
			sampleNumber: '17',
			baseUrl: serverUrl + '/samples/external/guitar-electric/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'A2': 'A2.mp3',
				'A3': 'A3.mp3',
				'A4': 'A4.mp3',
				'A5': 'A5.mp3',
				'C3': 'C3.mp3',
				'C4': 'C4.mp3',
				'C5': 'C5.mp3',
				'C6': 'C6.mp3',
				'C#2': 'Cs2.mp3',
				'D#3': 'Ds3.mp3',
				'D#4': 'Ds4.mp3',
				'D#5': 'Ds5.mp3',
				'E2': 'E2.mp3',
				'F#2': 'Fs2.mp3',
				'F#3': 'Fs3.mp3',
				'F#4': 'Fs4.mp3',
				'F#5': 'Fs5.mp3',
			},
		};

		instruments.set('Guitar Electric',instrument);


		/////////
		// Guitar Nylon ( samples/external/guitar-nylon/ )
			instrument  = {
			displayName: 'Guitar Nylon',
			sampleNumber: '29',
			baseUrl: serverUrl + '/samples/external/guitar-nylon/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'A2': 'A2.mp3',
				'A3': 'A3.mp3',
				'A4': 'A4.mp3',
				'A5': 'A5.mp3',
				'A#5': 'As5.mp3',
				'B1': 'B1.mp3',
				'B2': 'B2.mp3',
				'B3': 'B3.mp3',
				'B4': 'B4.mp3',
				'C#3': 'Cs3.mp3',
				'C#4': 'Cs4.mp3',
				'C#5': 'Cs5.mp3',
				'D2': 'D2.mp3',
				'D3': 'D3.mp3',
				'D5': 'D5.mp3',
				'D#4': 'Ds4.mp3',
				'E2': 'E2.mp3',
				'E3': 'E3.mp3',
				'E4': 'E4.mp3',
				'E5': 'E5.mp3',
				'F#2': 'Fs2.mp3',
				'F#3': 'Fs3.mp3',
				'F#4': 'Fs4.mp3',
				'F#5': 'Fs5.mp3',
				'G3': 'G3.mp3',
				'G5': 'G5.mp3',
				'G#2': 'Gs2.mp3',
				'G#4': 'Gs4.mp3',
				'G#5': 'Gs5.mp3',
			},
		};

		instruments.set('Guitar Nylon',instrument);


		/////////
		// Xylophone ( samples/external/xylophone/ )
			instrument  = {
			displayName: 'Xylophone',
			sampleNumber: '8',
			baseUrl: serverUrl + '/samples/external/xylophone/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'C5': 'C5.mp3',
				'C6': 'C6.mp3',
				'C7': 'C7.mp3',
				'C8': 'C8.mp3',
				'G4': 'G4.mp3',
				'G5': 'G5.mp3',
				'G6': 'G6.mp3',
				'G7': 'G7.mp3',
			},
		};

		instruments.set('Xylophone',instrument);


		/////////
		// Trumpet ( samples/external/trumpet/ )
			instrument  = {
			displayName: 'Trumpet',
			sampleNumber: '11',
			baseUrl: serverUrl + '/samples/external/trumpet/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'A3': 'A3.mp3',
				'A5': 'A5.mp3',
				'A#4': 'As4.mp3',
				'C4': 'C4.mp3',
				'C6': 'C6.mp3',
				'D5': 'D5.mp3',
				'D#4': 'Ds4.mp3',
				'F3': 'F3.mp3',
				'F4': 'F4.mp3',
				'F5': 'F5.mp3',
				'G4': 'G4.mp3',
			},
		};

		instruments.set('Trumpet',instrument);


		/////////
		// Bass Electric ( samples/external/bass-electric/ )
			instrument  = {
			displayName: 'Bass Electric',
			sampleNumber: '17',
			baseUrl: serverUrl + '/samples/external/bass-electric/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'A#1': 'As1.mp3',
				'A#2': 'As2.mp3',
				'A#3': 'As3.mp3',
				'A#4': 'As4.mp3',
				'C#1': 'Cs1.mp3',
				'C#2': 'Cs2.mp3',
				'C#3': 'Cs3.mp3',
				'C#4': 'Cs4.mp3',
				'C#5': 'Cs5.mp3',
				'E1': 'E1.mp3',
				'E2': 'E2.mp3',
				'E3': 'E3.mp3',
				'E4': 'E4.mp3',
				'G1': 'G1.mp3',
				'G2': 'G2.mp3',
				'G3': 'G3.mp3',
				'G4': 'G4.mp3',
			},
		};

		instruments.set('Bass Electric',instrument);


		/////////
		// Guitar Acoustic ( samples/external/guitar-acoustic/ )
			instrument  = {
			displayName: 'Guitar Acoustic',
			sampleNumber: '37',
			baseUrl: serverUrl + '/samples/external/guitar-acoustic/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'A2': 'A2.mp3',
				'A3': 'A3.mp3',
				'A4': 'A4.mp3',
				'A#2': 'As2.mp3',
				'A#3': 'As3.mp3',
				'A#4': 'As4.mp3',
				'B2': 'B2.mp3',
				'B3': 'B3.mp3',
				'B4': 'B4.mp3',
				'C3': 'C3.mp3',
				'C4': 'C4.mp3',
				'C5': 'C5.mp3',
				'C#3': 'Cs3.mp3',
				'C#4': 'Cs4.mp3',
				'C#5': 'Cs5.mp3',
				'D2': 'D2.mp3',
				'D3': 'D3.mp3',
				'D4': 'D4.mp3',
				'D5': 'D5.mp3',
				'D#2': 'Ds2.mp3',
				'D#3': 'Ds3.mp3',
				'D#4': 'Ds4.mp3',
				'E2': 'E2.mp3',
				'E3': 'E3.mp3',
				'E4': 'E4.mp3',
				'F2': 'F2.mp3',
				'F3': 'F3.mp3',
				'F4': 'F4.mp3',
				'F#2': 'Fs2.mp3',
				'F#3': 'Fs3.mp3',
				'F#4': 'Fs4.mp3',
				'G2': 'G2.mp3',
				'G3': 'G3.mp3',
				'G4': 'G4.mp3',
				'G#2': 'Gs2.mp3',
				'G#3': 'Gs3.mp3',
				'G#4': 'Gs4.mp3',
			},
		};

		instruments.set('Guitar Acoustic',instrument);


		/////////
		// Contrabass ( samples/external/contrabass/ )
			instrument  = {
			displayName: 'Contrabass',
			sampleNumber: '13',
			baseUrl: serverUrl + '/samples/external/contrabass/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'A2': 'A2.mp3',
				'A#1': 'As1.mp3',
				'B3': 'B3.mp3',
				'C2': 'C2.mp3',
				'C#3': 'Cs3.mp3',
				'D2': 'D2.mp3',
				'E2': 'E2.mp3',
				'E3': 'E3.mp3',
				'F#1': 'Fs1.mp3',
				'F#2': 'Fs2.mp3',
				'G1': 'G1.mp3',
				'G#2': 'Gs2.mp3',
				'G#3': 'Gs3.mp3',
			},
		};

		instruments.set('Contrabass',instrument);


		/////////
		// Cello ( samples/external/cello/ )
			instrument  = {
			displayName: 'Cello',
			sampleNumber: '35',
			baseUrl: serverUrl + '/samples/external/cello/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'A2': 'A2.mp3',
				'A3': 'A3.mp3',
				'A4': 'A4.mp3',
				'A#2': 'As2.mp3',
				'A#3': 'As3.mp3',
				'B2': 'B2.mp3',
				'B3': 'B3.mp3',
				'B4': 'B4.mp3',
				'C2': 'C2.mp3',
				'C3': 'C3.mp3',
				'C4': 'C4.mp3',
				'C5': 'C5.mp3',
				'C#3': 'Cs3.mp3',
				'C#4': 'Cs4.mp3',
				'D2': 'D2.mp3',
				'D3': 'D3.mp3',
				'D4': 'D4.mp3',
				'D#2': 'Ds2.mp3',
				'D#3': 'Ds3.mp3',
				'D#4': 'Ds4.mp3',
				'E2': 'E2.mp3',
				'E3': 'E3.mp3',
				'E4': 'E4.mp3',
				'F2': 'F2.mp3',
				'F3': 'F3.mp3',
				'F4': 'F4.mp3',
				'F#3': 'Fs3.mp3',
				'F#4': 'Fs4.mp3',
				'G2': 'G2.mp3',
				'G3': 'G3.mp3',
				'G4': 'G4.mp3',
				'G#2': 'Gs2.mp3',
				'G#4': 'Gs4.mp3',
			},
		};

		instruments.set('Cello',instrument);


		/////////
		// Tuba ( samples/external/tuba/ )
			instrument  = {
			displayName: 'Tuba',
			sampleNumber: '9',
			baseUrl: serverUrl + '/samples/external/tuba/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'A#1': 'As1.mp3',
				'A#2': 'As2.mp3',
				'A#3': 'As3.mp3',
				'D3': 'D3.mp3',
				'D4': 'D4.mp3',
				'D#2': 'Ds2.mp3',
				'F1': 'F1.mp3',
				'F2': 'F2.mp3',
				'F3': 'F3.mp3',
			},
		};

		instruments.set('Tuba',instrument);


		/////////
		// Clarinet ( samples/external/clarinet/ )
			instrument  = {
			displayName: 'Clarinet',
			sampleNumber: '11',
			baseUrl: serverUrl + '/samples/external/clarinet/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'A#3': 'As3.mp3',
				'A#4': 'As4.mp3',
				'A#5': 'As5.mp3',
				'D3': 'D3.mp3',
				'D4': 'D4.mp3',
				'D5': 'D5.mp3',
				'D6': 'D6.mp3',
				'F3': 'F3.mp3',
				'F4': 'F4.mp3',
				'F5': 'F5.mp3',
				'F#6': 'Fs6.mp3',
			},
		};

		instruments.set('Clarinet',instrument);


		/////////
		// Trombone ( samples/external/trombone/ )
			instrument  = {
			displayName: 'Trombone',
			sampleNumber: '17',
			baseUrl: serverUrl + '/samples/external/trombone/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'A#1': 'As1.mp3',
				'A#2': 'As2.mp3',
				'A#3': 'As3.mp3',
				'C3': 'C3.mp3',
				'C4': 'C4.mp3',
				'C#2': 'Cs2.mp3',
				'C#4': 'Cs4.mp3',
				'D3': 'D3.mp3',
				'D4': 'D4.mp3',
				'D#2': 'Ds2.mp3',
				'D#3': 'Ds3.mp3',
				'D#4': 'Ds4.mp3',
				'F2': 'F2.mp3',
				'F3': 'F3.mp3',
				'F4': 'F4.mp3',
				'G#2': 'Gs2.mp3',
				'G#3': 'Gs3.mp3',
			},
		};

		instruments.set('Trombone',instrument);


		/////////
		// Flute ( samples/external/flute/ )
			instrument  = {
			displayName: 'Flute',
			sampleNumber: '10',
			baseUrl: serverUrl + '/samples/external/flute/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'A4': 'A4.mp3',
				'A5': 'A5.mp3',
				'A6': 'A6.mp3',
				'C4': 'C4.mp3',
				'C5': 'C5.mp3',
				'C6': 'C6.mp3',
				'C7': 'C7.mp3',
				'E4': 'E4.mp3',
				'E5': 'E5.mp3',
				'E6': 'E6.mp3',
			},
		};

		instruments.set('Flute',instrument);


		/////////
		// Harmonium ( samples/external/harmonium/ )
			instrument  = {
			displayName: 'Harmonium',
			sampleNumber: '38',
			baseUrl: serverUrl + '/samples/external/harmonium/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'A2': 'A2.mp3',
				'A3': 'A3.mp3',
				'A4': 'A4.mp3',
				'A#2': 'As2.mp3',
				'A#3': 'As3.mp3',
				'A#4': 'As4.mp3',
				'B2': 'B2.mp3',
				'B3': 'B3.mp3',
				'B4': 'B4.mp3',
				'C2': 'C2.mp3',
				'C3': 'C3.mp3',
				'C4': 'C4.mp3',
				'C5': 'C5.mp3',
				'C#2': 'Cs2.mp3',
				'C#3': 'Cs3.mp3',
				'C#4': 'Cs4.mp3',
				'C#5': 'Cs5.mp3',
				'D2': 'D2.mp3',
				'D3': 'D3.mp3',
				'D4': 'D4.mp3',
				'D5': 'D5.mp3',
				'D#2': 'Ds2.mp3',
				'D#3': 'Ds3.mp3',
				'D#4': 'Ds4.mp3',
				'E2': 'E2.mp3',
				'E3': 'E3.mp3',
				'E4': 'E4.mp3',
				'F2': 'F2.mp3',
				'F3': 'F3.mp3',
				'F4': 'F4.mp3',
				'F#2': 'Fs2.mp3',
				'F#3': 'Fs3.mp3',
				'G2': 'G2.mp3',
				'G3': 'G3.mp3',
				'G4': 'G4.mp3',
				'G#2': 'Gs2.mp3',
				'G#3': 'Gs3.mp3',
				'G#4': 'Gs4.mp3',
			},
		};

		instruments.set('Harmonium',instrument);


		/////////
		// Violin ( samples/external/violin/ )
			instrument  = {
			displayName: 'Violin',
			sampleNumber: '15',
			baseUrl: serverUrl + '/samples/external/violin/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'A3': 'A3.mp3',
				'A4': 'A4.mp3',
				'A5': 'A5.mp3',
				'A6': 'A6.mp3',
				'C4': 'C4.mp3',
				'C5': 'C5.mp3',
				'C6': 'C6.mp3',
				'C7': 'C7.mp3',
				'E4': 'E4.mp3',
				'E5': 'E5.mp3',
				'E6': 'E6.mp3',
				'G3': 'G3.mp3',
				'G4': 'G4.mp3',
				'G5': 'G5.mp3',
				'G6': 'G6.mp3',
			},
		};

		instruments.set('Violin',instrument);


		/////////
		// French Horn ( samples/external/french-horn/ )
			instrument  = {
			displayName: 'French Horn',
			sampleNumber: '9',
			baseUrl: serverUrl + '/samples/external/french-horn/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'A3': 'A3.mp3',
				'C2': 'C2.mp3',
				'C4': 'C4.mp3',
				'D3': 'D3.mp3',
				'D5': 'D5.mp3',
				'D#2': 'Ds2.mp3',
				'F3': 'F3.mp3',
				'F5': 'F5.mp3',
				'G2': 'G2.mp3',
			},
		};

		instruments.set('French Horn',instrument);


		/////////
		// Washing One ( samples/mine/washing-one/ )
			instrument  = {
			displayName: 'Washing One',
			sampleNumber: '1',
			baseUrl: serverUrl + '/samples/mine/washing-one/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'G3': 'G3.mp3',
			},
		};

		instruments.set('Washing One',instrument);


		/////////
		// Doos ( samples/mine/doos/ )
			instrument  = {
			displayName: 'Doos',
			sampleNumber: '7',
			baseUrl: serverUrl + '/samples/mine/doos/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'C3': 'C3.mp3',
				'C4': 'C4.mp3',
				'D3': 'D3.mp3',
				'D4': 'D4.mp3',
				'E3': 'E3.mp3',
				'E4': 'E4.mp3',
				'G3': 'G3.mp3',
			},
		};

		instruments.set('Doos',instrument);


		/////////
		// Spueli ( samples/mine/spueli/ )
			instrument  = {
			displayName: 'Spueli',
			sampleNumber: '2',
			baseUrl: serverUrl + '/samples/mine/spueli/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'G2': 'G2.mp3',
				'G2_old': 'G2_old.mp3',
			},
		};

		instruments.set('Spueli',instrument);


		/////////
		// Fan ( samples/mine/fan/ )
			instrument  = {
			displayName: 'Fan',
			sampleNumber: '1',
			baseUrl: serverUrl + '/samples/mine/fan/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'D5': 'D5.mp3',
			},
		};

		instruments.set('Fan',instrument);


		/////////
		// Ahhs ( samples/mine/ahhs/ )
			instrument  = {
			displayName: 'Ahhs',
			sampleNumber: '6',
			baseUrl: serverUrl + '/samples/mine/ahhs/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'A3': 'A3.mp3',
				'C3': 'C3.mp3',
				'C4': 'C4.mp3',
				'D3': 'D3.mp3',
				'E3': 'E3.mp3',
				'G3': 'G3.mp3',
			},
		};

		instruments.set('Ahhs',instrument);


		/////////
		// Toothbrush ( samples/mine/toothbrush/ )
			instrument  = {
			displayName: 'Toothbrush',
			sampleNumber: '1',
			baseUrl: serverUrl + '/samples/mine/toothbrush/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'F4': 'F4.mp3',
			},
		};

		instruments.set('Toothbrush',instrument);


		/////////
		// Gas ( samples/mine/gas/ )
			instrument  = {
			displayName: 'Gas',
			sampleNumber: '1',
			baseUrl: serverUrl + '/samples/mine/gas/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'G2': 'G2.mp3',
			},
		};

		instruments.set('Gas',instrument);


		/////////
		// Washing Two ( samples/mine/washing-two/ )
			instrument  = {
			displayName: 'Washing Two',
			sampleNumber: '1',
			baseUrl: serverUrl + '/samples/mine/washing-two/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'G3': 'G3.mp3',
			},
		};

		instruments.set('Washing Two',instrument);


		/////////
		// Fridge ( samples/mine/fridge/ )
			instrument  = {
			displayName: 'Fridge',
			sampleNumber: '1',
			baseUrl: serverUrl + '/samples/mine/fridge/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'G1': 'G1.mp3',
			},
		};

		instruments.set('Fridge',instrument);


		/////////
		// Ukulele ( samples/mine/ukulele/ )
			instrument  = {
			displayName: 'Ukulele',
			sampleNumber: '5',
			baseUrl: serverUrl + '/samples/mine/ukulele/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'A4': 'A4.mp3',
				'C4': 'C4.mp3',
				'C5': 'C5.mp3',
				'E4': 'E4.mp3',
				'G4': 'G4.mp3',
			},
		};

		instruments.set('Ukulele',instrument);


		/////////
		// Pump ( samples/mine/pump/ )
			instrument  = {
			displayName: 'Pump',
			sampleNumber: '1',
			baseUrl: serverUrl + '/samples/mine/pump/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'G1': 'G1.mp3',
			},
		};

		instruments.set('Pump',instrument);


		/////////
		// Bottle ( samples/mine/bottle/ )
			instrument  = {
			displayName: 'Bottle',
			sampleNumber: '1',
			baseUrl: serverUrl + '/samples/mine/bottle/',
			attack: 0.01,
			release: 0.3,
			buffer: null,
			isBuffering: false,
			isBuffered: false,
			urls: {
				'D3': 'D3.mp3',
			},
		};

		instruments.set('Bottle',instrument);


		return instruments;
	}}


